### ISSUE TITLE
是否考虑更新该项目

### ISSUE THREAD

**Issue by sj817** [liujiaqi7998/genshinclienthelper#2]
是否可以为该项目添加简单的选定路径后通过识别md5然后自动注入补丁并一键启动代理和游戏，把该项目变成启动器项目

**Comment by liujiaqi7998** [comment]
这个项目已经弃更了，如果您感兴趣，可以随意拿来改

**Comment by sj817** [comment]
好吧谢谢，其实可以进行更新，该项目目前而言还是非常强大的。
